### ISSUE TITLE
ValueError: Unknown metric function: metric_F1score

### ISSUE THREAD

**Issue by updaun** [updaun/HandGestureRecognition#5]
- keras h5 model_load error
```
(mp) C:\Users\user\Desktop\Projects\Hand_Gesture_Recognition>C:/Users/user/anaconda3/envs/mp/python.exe c:/Users/user/Desktop/Projects/Hand_Gesture_Recognition/multi_hand_examples/webcam_test_model_keras.py
2022-05-22 20:39:25.607472: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-05-22 20:39:25.608116: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-05-22 20:39:28.324470: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-05-22 20:39:28.326001: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; 
dlerror: nvcuda.dll not found
2022-05-22 20:39:28.326414: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-22 20:39:28.330482: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-B9BCOUM
2022-05-22 20:39:28.331066: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-B9BCOUM
2022-05-22 20:39:28.332077: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-22 20:39:28.333898: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set  
Traceback (most recent call last):
  File "c:/Users/user/Desktop/Projects/Hand_Gesture_Recognition/multi_hand_examples/webcam_test_model_keras.py", line 15, in <module>
    model = load_model('models/not_applied_classifier.h5')
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\saving\save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 199, in load_model_from_hdf5
    model.compile(**saving_utils.compile_args_from_training_config(
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 224, in compile_args_from_training_config
    metrics = _deserialize_nested_config(_deserialize_metric, metrics_config)
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 266, in _deserialize_nested_config
    return [_deserialize_nested_config(deserialize_fn, obj) for obj in config]
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 266, in <listcomp>       
    return [_deserialize_nested_config(deserialize_fn, obj) for obj in config]
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 266, in _deserialize_nested_config
    return [_deserialize_nested_config(deserialize_fn, obj) for obj in config]
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 266, in <listcomp>       
    return [_deserialize_nested_config(deserialize_fn, obj) for obj in config]
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 259, in _deserialize_nested_config
    return deserialize_fn(config)
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 289, in _deserialize_metric
    return metrics_module.deserialize(metric_config)
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\metrics.py", line 3446, in deserialize
    return deserialize_keras_object(
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 360, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\metrics.py", line 641, in from_config
    return cls(get(fn), **config)
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\metrics.py", line 3490, in get
    return deserialize(str(identifier))
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\metrics.py", line 3446, in deserialize
    return deserialize_keras_object(
  File "C:\Users\user\anaconda3\envs\mp\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 377, in deserialize_keras_object
    raise ValueError(
ValueError: Unknown metric function: metric_F1score
```

**Comment by updaun** [comment]
- debug

```python
from tensorflow.keras.models import load_model
model = load_model('models/not_applied_classifier.h5')
```

```python
import tensorflow as tf
from tensorflow.keras.models import load_model
def metric_F1score(y_true,y_pred): 
    TP=tf.reduce_sum(y_true*tf.round(y_pred))
    TN=tf.reduce_sum((1-y_true)*(1-tf.round(y_pred)))
    FP=tf.reduce_sum((1-y_true)*tf.round(y_pred))
    FN=tf.reduce_sum(y_true*(1-tf.round(y_pred)))
    precision=TP/(TP+FP)
    recall=TP/(TP+FN)
    F1score=2*precision*recall/(precision+recall)
    return F1score

model = load_model('models/vector_normalization_classifier.h5',
                    custom_objects={'metric_F1score':metric_F1score})
```
